//! Full-IS parity gate — proves the populated IS body + dynamic BS/CF IS-refs
//! reproduce the Python `*_full_snapshot.json` oracles (generated by
//! `tieout/build_full_is_oracle.py`), across sectors.
//!
//! Inputs come from the committed empty-IS snapshot's `model_output`; the IS
//! structure is built explicitly per sector. IS/BS/CF are market-independent
//! (they reference Assumptions *cells*, not values), so the gate is
//! deterministic even though the oracle's market inputs came from live yfinance.

use fm_excel::is_structure::build_is_structure;
use fm_excel::sheets::build_workbook;
use fm_excel::snapshot::{compare_workbook, load_snapshot, workbook_input_from_snapshot};

const GATED: [&str; 3] = ["IS", "BS", "CF"];

/// (committed source, oracle file, sector). NESN excluded: null gross_profit in
/// its reconstructed historicals crashes the Python reference oracle-gen.
fn cases() -> Vec<(&'static str, String, &'static str)> {
    let mut v: Vec<(&str, String, &str)> = vec![
        ("SAND_ST", "SAND_ST_full".into(), "standard"),
        ("ASML_AS", "ASML_AS_full".into(), "standard"),
        ("NOVO-B_CO", "NOVO-B_CO_full".into(), "standard"),
        ("ATCO-B_ST", "ATCO-B_ST_full".into(), "standard"),
    ];
    for sector in ["utility", "bank", "insurance", "reit"] {
        v.push(("SAND_ST", format!("SAND_ST_{sector}_full"), sector));
    }
    v
}

fn path(name: &str) -> String {
    format!(
        "{}/../../tieout/excel_snapshots/{}_snapshot.json",
        env!("CARGO_MANIFEST_DIR"),
        name
    )
}

fn nonzero(mo: &serde_json::Value, key: &str) -> bool {
    mo["income_statement"][key]
        .as_array()
        .map(|a| {
            a.iter()
                .any(|v| v.as_f64().map(|n| n != 0.0).unwrap_or(false))
        })
        .unwrap_or(false)
}

#[test]
fn full_is_reproduces_oracle() {
    let mut failures: Vec<String> = Vec::new();

    for (committed_name, oracle_name, sector) in cases() {
        let committed = load_snapshot(&path(committed_name)).expect("committed snapshot");
        let oracle = load_snapshot(&path(&oracle_name)).expect("full oracle");

        let mut input = workbook_input_from_snapshot(&committed).expect("input");
        input.meta.sector = sector.to_string();
        let mo = &committed["model_output"];
        input.is_structure = build_is_structure(
            sector,
            nonzero(mo, "cogs"),
            nonzero(mo, "rd"),
            nonzero(mo, "sga"),
        );

        let wb = build_workbook(&input);
        for d in compare_workbook(&wb, &oracle) {
            if GATED.contains(&d.sheet.as_str()) {
                failures.push(format!("[{oracle_name}] {d}"));
            }
        }
    }

    if !failures.is_empty() {
        let shown: Vec<&str> = failures.iter().take(40).map(|s| s.as_str()).collect();
        panic!(
            "{} full-IS diffs on {:?}:\n{}",
            failures.len(),
            GATED,
            shown.join("\n")
        );
    }
}

/// Non-standard sectors relabel the Assumptions drivers (writer.py
/// `ASSUMP_DRIVERS_UTILITY`). The IS/BS/CF gate doesn't cover Assumptions labels,
/// so verify them directly against the utility oracle.
#[test]
fn sector_relabels_assumptions_drivers() {
    use fm_excel::model::Value;
    let committed = load_snapshot(&path("SAND_ST")).expect("committed");
    let oracle = load_snapshot(&path("SAND_ST_utility_full")).expect("utility oracle");

    let mut input = workbook_input_from_snapshot(&committed).expect("input");
    input.meta.sector = "utility".to_string();
    let mo = &committed["model_output"];
    input.is_structure = build_is_structure(
        "utility",
        nonzero(mo, "cogs"),
        nonzero(mo, "rd"),
        nonzero(mo, "sga"),
    );
    let wb = build_workbook(&input);
    let asmp = wb.sheet("Assumptions").expect("Assumptions");

    // C16/C17/C18 (0-based rows 15/16/17) are the relabeled active-block drivers.
    for (row, expected) in [
        (15u32, "  O&M % of Revenue"),
        (16, "  Taxes other than income % of Revenue"),
        (17, "  Other OpEx % of Revenue"),
    ] {
        let got = asmp.cells.get(&(row, 2)).and_then(|c| match &c.value {
            Some(Value::Text(t)) => Some(t.as_str()),
            _ => None,
        });
        assert_eq!(got, Some(expected), "Assumptions row {row} label");
        // Cross-check the oracle carries the same label.
        let oref = format!("C{}", row + 1);
        let orc = oracle["sheets"]["Assumptions"].as_array().and_then(|rows| {
            rows.iter()
                .flat_map(|r| r["cells"].as_array().cloned().unwrap_or_default())
                .find(|c| c["ref"] == oref)
                .and_then(|c| c["value"].as_str().map(String::from))
        });
        assert_eq!(orc.as_deref(), Some(expected), "oracle Assumptions {oref}");
    }
}

/// XBRL-detail gate: revenue segments + detailed COGS + extra opex items,
/// synthesized onto SAND (no US R-file fixtures exist). Proves the segment /
/// cogs_seg / opex_ structure + formulas match the Python oracle.
#[test]
fn xbrl_detail_reproduces_oracle() {
    use fm_excel::is_structure::{CogsDetail, OpexItem, Segment, build_standard_is_detailed};

    let oracle = load_snapshot(&path("SAND_ST_xbrl_full")).expect("xbrl oracle");
    let mut input = workbook_input_from_snapshot(&oracle).expect("input");

    let seg = |label: &str, key: &str| Segment {
        label: label.into(),
        key: key.into(),
    };
    let opx = |label: &str, key: &str, cat: &str| OpexItem {
        label: label.into(),
        key: key.into(),
        category: cat.into(),
    };
    let cd = |label: &str, key: &str| CogsDetail {
        label: label.into(),
        key: key.into(),
    };
    let segments = vec![seg("Products", "rev_seg_a"), seg("Services", "rev_seg_b")];
    let cogs_detail = vec![
        cd("Cost of products", "cogs_seg_a"),
        cd("Cost of services", "cogs_seg_b"),
    ];
    let opex_items = vec![
        opx("Cost of products", "cogs_seg_a", "cogs"),
        opx("Cost of services", "cogs_seg_b", "cogs"),
        opx("Research & Development", "rd", "opex_rd"),
        opx("Selling, General & Administrative", "sga", "opex"),
        opx("Marketing", "opex_marketing", "opex"),
    ];
    input.is_structure =
        build_standard_is_detailed(true, true, true, &segments, &opex_items, &cogs_detail);

    let wb = build_workbook(&input);
    let failures: Vec<String> = compare_workbook(&wb, &oracle)
        .into_iter()
        .filter(|d| GATED.contains(&d.sheet.as_str()))
        .map(|d| d.to_string())
        .collect();
    if !failures.is_empty() {
        let shown: Vec<&str> = failures.iter().take(40).map(|s| s.as_str()).collect();
        panic!(
            "{} XBRL-detail diffs:\n{}",
            failures.len(),
            shown.join("\n")
        );
    }
}
