//! Valuation-tab cell-level parity gate.
//!
//! Diffs Cover / DCF / WACC / Sensitivities against the Python oracle
//! `tieout/excel_snapshots/SAND_ST_val_full_snapshot.json` (generated by
//! `tieout/build_val_oracle.py`). The oracle embeds the exact WACCOutput /
//! DCFOutput payload the Python writer received, so this gates the *writer*
//! only — not the compute path.

use fm_excel::input::{AssumptionsBlock, Meta, ModelOutput, Verification, WorkbookInput};
use fm_excel::is_structure::build_is_structure;
use fm_excel::sheets::build_workbook;
use fm_excel::snapshot::{compare_workbook, load_snapshot};
use fm_value::{DCFOutput, Peer, WACCOutput};

const GATED: [&str; 4] = ["Cover", "DCF", "WACC", "Sensitivities"];

fn oracle_path() -> String {
    format!(
        "{}/../../tieout/excel_snapshots/SAND_ST_val_full_snapshot.json",
        env!("CARGO_MANIFEST_DIR")
    )
}

fn parse_statement(obj: &serde_json::Value) -> fm_excel::input::Statement {
    let mut out = fm_excel::input::Statement::new();
    if let Some(map) = obj.as_object() {
        for (k, v) in map {
            if let Some(arr) = v.as_array() {
                out.insert(k.clone(), arr.iter().map(|x| x.as_f64()).collect());
            }
        }
    }
    out
}

fn f64_field(v: &serde_json::Value, k: &str) -> f64 {
    v.get(k).and_then(|x| x.as_f64()).unwrap_or(0.0)
}

fn f64_vec(v: &serde_json::Value, k: &str) -> Vec<f64> {
    v.get(k)
        .and_then(|x| x.as_array())
        .map(|a| a.iter().filter_map(|x| x.as_f64()).collect())
        .unwrap_or_default()
}

fn f64_grid(v: &serde_json::Value, k: &str) -> Vec<Vec<f64>> {
    v.get(k)
        .and_then(|x| x.as_array())
        .map(|rows| {
            rows.iter()
                .map(|r| {
                    r.as_array()
                        .map(|a| a.iter().filter_map(|x| x.as_f64()).collect())
                        .unwrap_or_default()
                })
                .collect()
        })
        .unwrap_or_default()
}

fn parse_wacc(v: &serde_json::Value) -> WACCOutput {
    let peers = v
        .get("peers")
        .and_then(|p| p.as_array())
        .map(|arr| {
            arr.iter()
                .map(|p| Peer {
                    ticker: p.get("ticker").and_then(|x| x.as_str()).unwrap_or("").into(),
                    name: p.get("name").and_then(|x| x.as_str()).unwrap_or("").into(),
                    market_cap: f64_field(p, "market_cap"),
                    enterprise_value: f64_field(p, "enterprise_value"),
                    levered_beta: f64_field(p, "levered_beta"),
                    de_ratio: f64_field(p, "de_ratio"),
                    tax_rate: f64_field(p, "tax_rate"),
                    rationale: p
                        .get("rationale")
                        .and_then(|x| x.as_str())
                        .unwrap_or("")
                        .into(),
                })
                .collect()
        })
        .unwrap_or_default();
    WACCOutput {
        peers,
        median_unlevered_beta: f64_field(v, "median_unlevered_beta"),
        target_levered_beta: f64_field(v, "target_levered_beta"),
        target_de_ratio: f64_field(v, "target_de_ratio"),
        risk_free_rate: f64_field(v, "risk_free_rate"),
        equity_risk_premium: f64_field(v, "equity_risk_premium"),
        cost_of_equity: f64_field(v, "cost_of_equity"),
        cost_of_debt_pretax: f64_field(v, "cost_of_debt_pretax"),
        tax_rate: f64_field(v, "tax_rate"),
        after_tax_cost_of_debt: f64_field(v, "after_tax_cost_of_debt"),
        target_market_cap: f64_field(v, "target_market_cap"),
        target_debt: f64_field(v, "target_debt"),
        target_total_capital: f64_field(v, "target_total_capital"),
        equity_weight: f64_field(v, "equity_weight"),
        debt_weight: f64_field(v, "debt_weight"),
        wacc: f64_field(v, "wacc"),
    }
}

fn parse_dcf(v: &serde_json::Value) -> DCFOutput {
    DCFOutput {
        ticker: v.get("ticker").and_then(|x| x.as_str()).unwrap_or("").into(),
        mid_year_convention: v
            .get("mid_year_convention")
            .and_then(|x| x.as_bool())
            .unwrap_or(true),
        beta: f64_field(v, "beta"),
        risk_free_rate: f64_field(v, "risk_free_rate"),
        equity_risk_premium: f64_field(v, "equity_risk_premium"),
        cost_of_equity: f64_field(v, "cost_of_equity"),
        cost_of_debt_pretax: f64_field(v, "cost_of_debt_pretax"),
        tax_rate: f64_field(v, "tax_rate"),
        after_tax_cost_of_debt: f64_field(v, "after_tax_cost_of_debt"),
        equity_weight: f64_field(v, "equity_weight"),
        debt_weight: f64_field(v, "debt_weight"),
        wacc: f64_field(v, "wacc"),
        proj_periods: v
            .get("proj_periods")
            .and_then(|x| x.as_array())
            .map(|a| {
                a.iter()
                    .filter_map(|x| x.as_str().map(String::from))
                    .collect()
            })
            .unwrap_or_default(),
        fcff_proj: f64_vec(v, "fcff_proj"),
        dwc_proj: f64_vec(v, "dwc_proj"),
        discount_factors: f64_vec(v, "discount_factors"),
        pv_fcfs_per_period: f64_vec(v, "pv_fcfs_per_period"),
        pv_fcfs: f64_field(v, "pv_fcfs"),
        terminal_ebitda: f64_field(v, "terminal_ebitda"),
        tv_ebitda_multiple: f64_field(v, "tv_ebitda_multiple"),
        tv_ebitda: f64_field(v, "tv_ebitda"),
        tv_ebitda_pv: f64_field(v, "tv_ebitda_pv"),
        tv_growth_rate: f64_field(v, "tv_growth_rate"),
        tv_gordon: f64_field(v, "tv_gordon"),
        tv_gordon_pv: f64_field(v, "tv_gordon_pv"),
        tv_method: v.get("tv_method").and_then(|x| x.as_i64()).unwrap_or(1) as i32,
        tv_selected: f64_field(v, "tv_selected"),
        pv_tv: f64_field(v, "pv_tv"),
        enterprise_value: f64_field(v, "enterprise_value"),
        total_debt: f64_field(v, "total_debt"),
        preferred_stock: f64_field(v, "preferred_stock"),
        noncontrolling_interest: f64_field(v, "noncontrolling_interest"),
        cash: f64_field(v, "cash"),
        investments: f64_field(v, "investments"),
        net_debt: f64_field(v, "net_debt"),
        equity_value: f64_field(v, "equity_value"),
        shares_diluted: f64_field(v, "shares_diluted"),
        implied_price: f64_field(v, "implied_price"),
        current_share_price: f64_field(v, "current_share_price"),
        upside_downside_pct: f64_field(v, "upside_downside_pct"),
        tv_pct_of_ev: f64_field(v, "tv_pct_of_ev"),
        wacc_minus_g: f64_field(v, "wacc_minus_g"),
        implied_exit_mult_from_gordon: f64_field(v, "implied_exit_mult_from_gordon"),
        implied_g_from_exit_mult: f64_field(v, "implied_g_from_exit_mult"),
        wacc_range: f64_vec(v, "wacc_range"),
        ebitda_multiple_range: f64_vec(v, "ebitda_multiple_range"),
        gordon_growth_range: f64_vec(v, "gordon_growth_range"),
        sensitivity_ebitda: f64_grid(v, "sensitivity_ebitda"),
        sensitivity_gordon: f64_grid(v, "sensitivity_gordon"),
    }
}

fn input_from_val_oracle(snap: &serde_json::Value) -> WorkbookInput {
    let mo = &snap["model_output"];
    let periods: Vec<String> = snap["periods"]
        .as_array()
        .unwrap()
        .iter()
        .filter_map(|v| v.as_str().map(String::from))
        .collect();
    let market = &snap["market"];
    let flags = &snap["is_flags"];

    let model = ModelOutput {
        periods: periods.clone(),
        income_statement: parse_statement(&mo["income_statement"]),
        balance_sheet: parse_statement(&mo["balance_sheet"]),
        cash_flow_statement: parse_statement(&mo["cash_flow_statement"]),
        plug_used: false,
    };

    // Rebuild assumptions from the frozen market block + derived drivers.
    // Sector standard; risk-free / share price frozen to match the oracle.
    let mut assumptions: AssumptionsBlock = fm_excel::derive::build_assumptions_block(
        &model,
        "standard",
        f64_field(market, "risk_free_rate"),
        f64_field(market, "current_share_price"),
    );
    assumptions.mid_year_convention = market
        .get("mid_year_convention")
        .and_then(|x| x.as_bool())
        .unwrap_or(true);
    // Align shared scalars with the oracle's market block (writer reads these).
    assumptions.equity_risk_premium = f64_field(market, "equity_risk_premium");
    assumptions.target_de_ratio = f64_field(market, "target_de_ratio");
    assumptions.cost_of_debt_pretax = f64_field(market, "cost_of_debt_pretax");
    assumptions.shares_diluted = f64_field(market, "shares_diluted");

    let meta = Meta {
        company: snap
            .get("company")
            .and_then(|x| x.as_str())
            .unwrap_or("Sandvik AB")
            .into(),
        ticker: snap
            .get("ticker")
            .and_then(|x| x.as_str())
            .unwrap_or("SAND.ST")
            .into(),
        currency: snap
            .get("currency")
            .and_then(|x| x.as_str())
            .unwrap_or("SEK")
            .into(),
        fiscal_year_end: "Dec".into(),
        sector: "standard".into(),
        // Cover as-of is date.today() in Python — not gated (value-only Cover C6).
        as_of: "1970-01-01".into(),
    };

    let is_structure = build_is_structure(
        "standard",
        flags
            .get("has_cogs")
            .and_then(|x| x.as_bool())
            .unwrap_or(true),
        flags.get("has_rd").and_then(|x| x.as_bool()).unwrap_or(true),
        flags
            .get("has_sga")
            .and_then(|x| x.as_bool())
            .unwrap_or(true),
    );

    WorkbookInput {
        meta,
        model,
        assumptions,
        verification: Verification {
            passed: true,
            ..Default::default()
        },
        is_structure,
        wacc: Some(parse_wacc(&snap["wacc_output"])),
        peer_source: snap
            .get("peer_source")
            .and_then(|x| x.as_str())
            .unwrap_or("synthetic")
            .into(),
        dcf: Some(parse_dcf(&snap["dcf_output"])),
    }
}

#[test]
fn valuation_tabs_reproduce_oracle() {
    let oracle = load_snapshot(&oracle_path()).expect("val oracle");
    let input = input_from_val_oracle(&oracle);
    let wb = build_workbook(&input);

    let names: Vec<&str> = wb.sheets.iter().map(|s| s.name.as_str()).collect();
    assert_eq!(
        names,
        [
            "Cover",
            "Assumptions",
            "IS",
            "BS",
            "CF",
            "DCF",
            "WACC",
            "Sensitivities",
            "Sources"
        ]
    );

    let mut failures: Vec<String> = Vec::new();
    for d in compare_workbook(&wb, &oracle) {
        if GATED.contains(&d.sheet.as_str()) {
            // Cover C6 "As of …" embeds today's date — skip value-only drift there.
            if d.sheet == "Cover" && d.reference == "C6" {
                continue;
            }
            failures.push(format!("{d}"));
        }
    }

    if !failures.is_empty() {
        let shown: Vec<&str> = failures.iter().take(60).map(|s| s.as_str()).collect();
        panic!(
            "{} valuation diffs on {:?}:\n{}",
            failures.len(),
            GATED,
            shown.join("\n")
        );
    }
}
