"""
3-Statement Accounting Rules ported from accounting-3-statements.json.
Rules ACC-001 through ACC-039, 28 formulas.
"""

from dataclasses import dataclass, field


@dataclass
class AccountingRule:
    id: str
    topic: str
    description: str


RULES = {
    "ACC-001": AccountingRule(id="ACC-001", topic="Income statement criteria",
        description="Two criteria: period matching (revenue/expense in period incurred) + common shareholder impact."),
    "ACC-002": AccountingRule(id="ACC-002", topic="Income statement structure",
        description="Revenue - COGS - OpEx = Operating Income + Other Income - Interest - Taxes = Net Income."),
    "ACC-003": AccountingRule(id="ACC-003", topic="Working capital definition",
        description="Current Operational Assets - Current Operational Liabilities (excl Cash/Debt)."),
    "ACC-004": AccountingRule(id="ACC-004", topic="Accounts receivable",
        description="AR increases = revenue recognized but cash not collected. Cash flow: -Delta AR."),
    "ACC-005": AccountingRule(id="ACC-005", topic="Accounts payable",
        description="AP increases = expense recognized but cash not paid. Cash flow: +Delta AP."),
    "ACC-006": AccountingRule(id="ACC-006", topic="Inventory",
        description="Purchase: no IS impact (asset swap). Sale: Revenue + COGS recognized."),
    "ACC-007": AccountingRule(id="ACC-007", topic="Prepaid expenses",
        description="Cash paid upfront, expense deferred. Asset decreases as expense recognized."),
    "ACC-008": AccountingRule(id="ACC-008", topic="Deferred revenue",
        description="Cash collected upfront, revenue deferred. Liability decreases as revenue recognized."),
    "ACC-009": AccountingRule(id="ACC-009", topic="CapEx vs OpEx",
        description="CapEx: useful life >1 year, capitalized on BS, depreciated over life. OpEx: expensed immediately."),
    "ACC-010": AccountingRule(id="ACC-010", topic="Depreciation methods",
        description="Straight-line (constant) vs Accelerated (front-loaded). Accelerated creates DTL (tax vs book timing)."),
    "ACC-011": AccountingRule(id="ACC-011", topic="Depreciation on 3 statements",
        description="IS: NI down by Depr*(1-t). CFS: Depr added back (non-cash). BS: Cash up by t*Depr, PP&E down by Depr."),
    "ACC-012": AccountingRule(id="ACC-012", topic="Debt issuing",
        description="Financing event. BS: Cash up, Debt up. IS: Interest expense. CFS: CFF inflow, CFO outflow (interest)."),
    "ACC-013": AccountingRule(id="ACC-013", topic="Equity issuing",
        description="BS: Cash up, CSE up. IS: No impact. CFS: CFF inflow. EPS diluted by new shares."),
    "ACC-014": AccountingRule(id="ACC-014", topic="Dividends vs stock repurchases",
        description="Both CFF. Dividends: RE down. Repurchases: Treasury stock up, share count down."),
    "ACC-015": AccountingRule(id="ACC-015", topic="Preferred stock",
        description="Fixed coupon on IS (not tax-deductible). CFF for issuance/repayment. Added in EV bridge."),
    "ACC-016": AccountingRule(id="ACC-016", topic="Lease classification",
        description=">12 months: Finance vs Operating. Tests: ownership transfer, bargain purchase, 75% economic life, 90% FV."),
    "ACC-017": AccountingRule(id="ACC-017", topic="Finance lease accounting",
        description="IS: Interest + Depreciation. CFS: Interest in CFO, principal in CFF. BS: ROU asset + lease liability."),
    "ACC-018": AccountingRule(id="ACC-018", topic="US GAAP operating lease",
        description="IS: Single rental expense (straight-line). BS: ROU asset + lease liability decrease by same amount. ASC 842."),
    "ACC-019": AccountingRule(id="ACC-019", topic="IFRS operating lease",
        description="Same as Finance lease: Interest + Depreciation on IS. No single rental expense. IFRS 16."),
    "ACC-020": AccountingRule(id="ACC-020", topic="Financial investments",
        description="CFI for purchase. Interest/Gain on IS. FV changes: Trading (IS), AFS (OCI), HTM (amortized cost)."),
    "ACC-021": AccountingRule(id="ACC-021", topic="Deferred tax creation",
        description="Book vs Tax timing differences create DTA/DTL. DTA: future deductible. DTL: future taxable."),
    "ACC-022": AccountingRule(id="ACC-022", topic="Net operating losses",
        description="NOL = accumulated negative Pre-Tax Income. DTA = NOL x Tax Rate. Subject to valuation allowance."),
    "ACC-023": AccountingRule(id="ACC-023", topic="Non-cash expense (book vs tax)",
        description="SBC, impairments, amortization: non-cash on IS, not tax-deductible until realized. Creates DTA."),
    "ACC-024": AccountingRule(id="ACC-024", topic="Gain/loss on asset sale",
        description="Gain on IS. Reversed on CFO (non-cash). Full proceeds in CFI. Book value removed from BS."),
    "ACC-025": AccountingRule(id="ACC-025", topic="Asset write-down/impairment",
        description="Non-cash IS expense. Reduces asset on BS. NOT cash-tax deductible until asset sold/disposed."),
    "ACC-026": AccountingRule(id="ACC-026", topic="Goodwill impairment",
        description="Annual test (or trigger-based). Non-cash, not tax-deductible. Reduces goodwill on BS."),
    "ACC-027": AccountingRule(id="ACC-027", topic="Stock-based compensation",
        description="IS expense (non-cash). Creates DTA (tax deduction when exercised). Dilutes shares (TSM)."),
    "ACC-028": AccountingRule(id="ACC-028", topic="Treasury stock method",
        description="Net dilution = Options - (Proceeds / Share Price). Proceeds = Exercise Price x Options."),
    "ACC-029": AccountingRule(id="ACC-029", topic="Goodwill in acquisition",
        description="Purchase Price - Fair Value of Net Identifiable Assets. Residual after purchase price allocation."),
    "ACC-030": AccountingRule(id="ACC-030", topic="Intangible amortization",
        description="Finite life: amortized straight-line. Non-cash IS expense. Added back on CFS."),
    "ACC-031": AccountingRule(id="ACC-031", topic="GAAP vs IFRS IS differences",
        description="Names differ. Lease treatment differs (IFRS 16 single model vs ASC 842 dual). Extraordinary items: GAAP allows, IFRS doesn't."),
    "ACC-032": AccountingRule(id="ACC-032", topic="GAAP vs IFRS CFS differences",
        description="IFRS may start with Operating Income (not Net Income). Interest/dividends: IFRS flexible classification, GAAP fixed."),
    "ACC-033": AccountingRule(id="ACC-033", topic="3-statement linking",
        description="Net Income -> CFS top (or Operating Income for IFRS). CFS bottom = Change in Cash -> BS Cash. BS must balance A = L + E."),
    "ACC-034": AccountingRule(id="ACC-034", topic="CFO vs CFI vs CFF",
        description="CFO: operations. CFI: long-term assets/investments. CFF: debt/equity financing. Always verify actual presentation."),
    "ACC-035": AccountingRule(id="ACC-035", topic="Free cash flow definition",
        description="FCF = CFO - CapEx. Unlevered FCF = EBIT*(1-t) + D&A +/- Change WC - CapEx."),
    "ACC-036": AccountingRule(id="ACC-036", topic="FCF drivers analysis",
        description="Revenue growth, margin expansion, working capital efficiency, CapEx discipline. Good FCF: driven by ops, not WC swings."),
    "ACC-037": AccountingRule(id="ACC-037", topic="Cash conversion metrics",
        description="DSO = AR/Rev*365. DIO = Inv/COGS*365. DPO = AP/COGS*365. CCC = DSO + DIO - DPO."),
    "ACC-038": AccountingRule(id="ACC-038", topic="Returns-based metrics",
        description="ROE = NI/Avg Equity (DuPont: Margin x Turnover x Leverage). ROA = NI/Avg Assets. ROIC = NOPAT/Avg Invested Capital."),
    "ACC-039": AccountingRule(id="ACC-039", topic="Credit metrics",
        description="Leverage = Debt/EBITDA. Interest Coverage = EBITDA/Interest. DSCR = EBITDA/(Interest + Principal)."),
}


FORMULAS = {
    "A-F-001": "Straight-Line Depreciation = (Cost - Salvage) / Useful Life",
    "A-F-002": "PV of Lease Payments = Sum(Payment_t / (1 + r)^t)",
    "A-F-003": "Finance Lease Interest = Lease Liability_begin x Discount Rate",
    "A-F-004": "Lease Principal Repayment = Cash Payment - Interest",
    "A-F-005": "Lease Depreciation = ROU Asset / Lease Term",
    "A-F-006": "DSO = Accounts Receivable / Revenue x 365",
    "A-F-007": "DIO = Inventory / COGS x 365",
    "A-F-008": "DPO = Accounts Payable / COGS x 365",
    "A-F-009": "CCC = DSO + DIO - DPO",
    "A-F-010": "ROE = Net Income / Average Common Equity",
    "A-F-011": "ROA = Net Income / Average Total Assets",
    "A-F-012": "ROIC = NOPAT / Average Invested Capital",
    "A-F-013": "Leverage Ratio = Total Debt / EBITDA",
    "A-F-014": "Interest Coverage = EBITDA / Interest Expense",
    "A-F-015": "FCF = CFO - CapEx",
    "A-F-016": "Change in WC = (AR_end + Inv_end - AP_end) - (AR_begin + Inv_begin - AP_begin)",
    "A-F-017": "NOPAT = EBIT x (1 - Tax Rate)",
    "A-F-018": "UFCF = EBIT x (1-t) + D&A +/- Change WC - CapEx",
    "A-F-019": "Cash from Asset Sale = Book Value + Gain (pre-tax, recorded in CFI)",
    "A-F-020": "Goodwill = Purchase Price - Fair Value of Net Assets",
    "A-F-021": "DTA from NOL = NOL x Tax Rate (subject to valuation allowance)",
    "A-F-022": "COGS (FIFO) = Oldest inventory cost layers",
    "A-F-023": "COGS (LIFO) = Newest inventory cost layers",
    "A-F-024": "Net Debt = Total Debt - Cash & Equivalents",
    "A-F-025": "Equity Value = Share Price x Diluted Shares",
    "A-F-026": "Enterprise Value = Equity Value + Net Debt + Leases + Pension + NCI + Preferred",
    "A-F-027": "TSM Net Shares = Options - (Exercise Price x Options) / Share Price",
    "A-F-028": "BVPS = Common Equity / Shares Outstanding",
}


# Key rule lookups by topic
RULE_LOOKUP = {
    "leases": ["ACC-016", "ACC-017", "ACC-018", "ACC-019"],
    "working_capital": ["ACC-003", "ACC-004", "ACC-005", "ACC-006", "ACC-007", "ACC-008"],
    "depreciation": ["ACC-009", "ACC-010", "ACC-011"],
    "debt": ["ACC-012"],
    "equity": ["ACC-013", "ACC-014", "ACC-015"],
    "deferred_tax": ["ACC-021", "ACC-022"],
    "impairment": ["ACC-025", "ACC-026"],
    "ma_accounting": ["ACC-029", "ACC-030"],
    "cash_flow": ["ACC-033", "ACC-034", "ACC-035", "ACC-036"],
    "metrics": ["ACC-037", "ACC-038", "ACC-039"],
}
